const mongoose=require('mongoose')

const orderSchema=mongoose.Schema({

   shippingInfo:{
        address:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        pincode:{
            type:Number,
            required:true
        },
        phoneno:{
            type:Number,
            required:true
        },
    },
    orderItems:[
        {
            name:{
                type:String,
                required:true
            },
            price:{
                type:Number,
                required:true
            },
            quantity:{
                type:Number,
                required:true
            },
            image:{
                type:String,
            },
            product:{
                type:mongoose.Schema.ObjectId,
                ref:"product",
                required:true
            }
        }
    ],

    user:{
        type:mongoose.Schema.ObjectId,
        ref:"user",
        required:true
    },
    
    paymentInfo:{
        id:{
            type:String,
            required:true
        },
        status:{
            type:String,
            required:true,
            default:"processing"
        },
        payat:{
            type:Date,
            required:true
        },
        itemprice:{
            type:Number,
            required:true,
            default:0
        },
        taxprice:{
            type:Number,
            required:true,
            default:0
        },
        shippingprice:{
            type:Number,
            required:true,
            default:0
        },
        totalprice:{
            type:Number,
            required:true,
            default:0
        }
    },
    orderStatus:{
        type:String,
        required:true,
        default:"processing"
    },
    deliveryAt:{
        type:Date,

    },
    createdAt:{
        type:Date,
        default:Date.now(),
        required:true
    }

})

module.exports=mongoose.model('order',orderSchema)